[vms.gnomewp]
node = "bingus"
vmid = 101

[vms.gooberbastion]
vmid = 105
node="bingus"

[vms.fjact]
vmid=106
node="bingus"

[vms.searxng]
vmid=114
node="bingus"

[vms.jellyfin]
vmid=108
node="bingus"

[vms.uptime]
vmid=110
node="bingus"

[vms.fleetn]
vmid=112
node="bingus"

[vms.searxng]
vmid=114
node="bingus"

[vms.immich]
vmid=119
node="bingus"

[vms.minecraft]
vmid=120
node="bingus"

[vms.guacamole]
vmid=127
node="bingus"

[vms.archmirror]
vmid=133
node="bingus"

[vms.freeproxy]
vmid=420
node="bingus"


## END BINGUS

[vms.dockerboy]
node = "cispve"
vmid = 100

[vms.gitserver]
node="cispve"
vmid=102

[vms.homeass]
node="cispve"
vmid=103

[vms.forgejo]
node="cispve"
vmid=104

[vms.glance]
node="cispve"
vmid=109

[vms.renovate]
node="cispve"
vmid=115

[vms.forgejorunner]
node="cispve"
vmid=116

[vms.beszel]
node="cispve"
vmid=122

[vms.crimebox]
node="cispve"
vmid=138

[vms.mgmt]
node="cispve"
vmid = 6969
